wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.1
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.6.13
    start_time: 1631531810
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 2
      4: 3.6.13
      5: 0.12.1
      8:
      - 1
      - 5
batch_size:
  desc: null
  value: 25
d_lr:
  desc: null
  value: 0.0001
d_units:
  desc: null
  value: 16
dataset:
  desc: null
  value: sinusoid
deeper:
  desc: null
  value: 0
device:
  desc: null
  value: cpu
e_lr:
  desc: null
  value: 0.001
hidden_size:
  desc: null
  value: 8
lam:
  desc: null
  value: 1
model_config:
  desc: null
  value: Config/debug.yaml
model_name:
  desc: null
  value: ACL
model_name_impv:
  desc: null
  value: ACL
n_steps_per_task:
  desc: null
  value: 1
num_batches:
  desc: null
  value: 100
num_domains:
  desc: null
  value: 3
num_epochs:
  desc: null
  value: 50
num_shots:
  desc: null
  value: 5
num_shots_test:
  desc: null
  value: 15
num_ways:
  desc: null
  value: 5
patience:
  desc: null
  value: 5
prob_statio:
  desc: null
  value: 0.98
s_layers:
  desc: null
  value: 0
s_units:
  desc: null
  value: 16
seed:
  desc: null
  value: 100
task_sequence:
  desc: null
  value: null
timesteps:
  desc: null
  value: 10000
verbose:
  desc: null
  value: false
wandb:
  desc: null
  value: false
wandb_group:
  desc: null
  value: ACL_0.98
wandb_key:
  desc: null
  value: null
wandb_name:
  desc: null
  value: null
wandb_project:
  desc: null
  value: null
